head:
  resources:
    limits:
      cpu: "1"
      memory: "4G"
    requests:
      cpu: "1"
      memory: "2G"

worker:
  replicas: 2
  minReplicas: 1
  maxReplicas: 3
  resources:
    limits:
      cpu: "1"
      memory: "1G"
    requests:
      cpu: "1"
      memory: "1G"